environment:
  TOKEN:
    secure: rY5dFN8j33FwsBgE6oq+X8T5XHbih1AkjfeN9byHjOAXHvW/TsX/Er3nD/A92RpLRpUYbVxyt5iAUdbkKQCKNg==

install:
  - npm install
  - npm install -g vsce

build_script:
  - echo publish package
  - vsce publish -p %TOKEN% || true
