environment:
  TOKEN:
    secure: AEieFFfW4iVmHm183DbTz0N+BuarsuEP0tajcoWIbM+YKIxDQmJ8F/6sofRkEczb0ezsnPHObahK7S88t3e0oA==

install:
  - npm install
  - npm install -g vsce

build_script:
  - echo publish package
  - vsce publish -p %TOKEN% || true
